# Generated by Django 2.2.14 on 2021-01-22 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_number', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_class', models.CharField(choices=[('B', 'buy'), ('S', 'sell')], max_length=1)),
                ('item_class', models.CharField(choices=[('p', 'phone'), ('mb', 'macbook'), ('m', 'mac'), ('ip', 'ipad'), ('ap', 'airpods'), ('oth', 'other')], max_length=2)),
                ('item_city_1', models.CharField(max_length=10)),
                ('item_city_2', models.CharField(blank=True, max_length=10, null=True)),
                ('item_year', models.DateField()),
                ('item_price', models.PositiveIntegerField()),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('warranty', models.BooleanField()),
                ('trade', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('label', models.CharField(choices=[('10', 'discount 10%'), ('5', 'discount 5%')], max_length=1)),
                ('article_datetime', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='core.UserProfile')),
            ],
        ),
    ]
