# Generated by Django 2.2.14 on 2021-01-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_year',
            field=models.PositiveIntegerField(max_length=4),
        ),
    ]
