# Generated by Django 2.2.14 on 2021-01-27 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210127_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_city_2',
        ),
    ]
