# Generated by Django 2.2.14 on 2021-01-27 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_remove_item_item_city_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='bs_class',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.AddField(
            model_name='item',
            name='sell_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sell_item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_class',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('10', 'discount 10%'), ('5', 'discount 5%')], max_length=1, null=True),
        ),
    ]
