# Generated by Django 2.2.14 on 2021-01-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210127_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_city_1',
            new_name='item_city',
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('10', 'discount 10%'), ('5', 'discount 5%')], default=None, max_length=1, null=True),
        ),
    ]
