# Generated by Django 2.2.14 on 2021-01-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210127_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_year',
            field=models.PositiveIntegerField(),
        ),
    ]
