# Generated by Django 2.2.14 on 2021-01-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210127_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
